name: CI/CD for the dockerized app

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag flasktest-app:date +%s
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run tests
      run: pytest

  build-and-push-image:
    needs: build-and-test
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push the image
      id: docker_build  # ✅ Added missing ID
      uses: docker/build-push-action@v2  # ✅ Upgraded to latest version
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest  # ✅ Correct format

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}  # ✅ Now it works correctly!
